github: myGitHubUser
patreon: myPatreonUser
open_collective: myOpenCollectiveUser
ko_fi: myKofiUser
tidelift: package-tidelift
community_bridge: myCommunityBridgeProject
liberapay: myLiberapayUser
issuehunt: myIssueHuntUser
otechie: myOtechieUser
custom: ['https://www.yourcustomsponsorlink.com']

